중국 : 510300.ss \
유럽 : EUE.DE \
일본 : 1321.T \
미국 : SPY

In [4]:
import os
import glob

import pandas as pd

In [12]:
def read_csv_files(nation, market, tickers=None):
    base_path = os.path.abspath(f'../stock_data/{nation}/{market}')
    all_files = glob.glob(os.path.join(base_path, "*.csv"))

    # tickers가 주어지면 해당 ticker만 필터링
    if tickers is not None:
        tickers = set(tickers)
        all_files = [f for f in all_files if os.path.splitext(os.path.basename(f))[0] in tickers]

    ticker_list = []
    for file_path in all_files:
        ticker = os.path.splitext(os.path.basename(file_path))[0]
        ticker_list.append(ticker)

    return ticker_list

### 한국

In [37]:
ks_ticker_list = read_csv_files("대한민국", "KOSPI")
ks_ticker_list = [s.removesuffix(".KS") for s in ks_ticker_list]

In [ ]:
df = pd.read_csv("../stock_data/etf_holdings_list/069500.KS_Holdings.csv", encoding="cp949")
df

             종목코드    구성종목명  주식수(계약수)         평가금액       시가총액  시가총액 구성비중
0          005930     삼성전자    7098.0  650176800.0  674310000      26.29
1          000660   SK하이닉스     851.0  350186500.0  359547500      14.02
2          105560     KB금융     491.0   54451900.0   56808700       2.21
3          034020  두산에너빌리티     650.0   49270000.0   53885000       2.10
4          035420    NAVER     197.0   50826000.0   50924500       1.99
..            ...      ...       ...          ...        ...        ...
196        003030   세아제강지주       2.0     285800.0     285800       0.01
197        006040     동원산업       6.0     253800.0     257400       0.01
198        014820   동원시스템즈       8.0     222000.0     223200       0.01
199        268280    미원에스씨       1.0     136500.0     135800       0.01
200  KRD010010001     원화현금       NaN          NaN    5255875       0.20

[201 rows x 6 columns]

In [ ]:
# 필요한 열만 남기고 비중 기준으로 내림차순 정렬
cols = ["구성종목명", "종목코드", "시가총액 구성비중"]
df = df[cols].copy()
df["시가총액 구성비중"] = pd.to_numeric(df["시가총액 구성비중"], errors="coerce")

df_ks = df.dropna(subset=["시가총액 구성비중"]).sort_values(
    "시가총액 구성비중", ascending=False).reset_index(drop=True)
# df_ks = df_ks.iloc[2:].reset_index(drop=True)
df_ks.head()

     구성종목명    종목코드  시가총액 구성비중
0     삼성전자  005930      26.29
1   SK하이닉스  000660      14.02
2     KB금융  105560       2.21
3  두산에너빌리티  034020       2.10
4    NAVER  035420       1.99

In [45]:
cnt = 0
ks_top_list = []

for ticker in df_ks['종목코드']:
    if cnt == 40:
        break
    if ticker in ks_ticker_list:
        ks_top_list.append(ticker)
        cnt += 1

In [47]:
len(ks_top_list)

40

In [51]:
print(", ".join(ks_top_list))

005930, 000660, 105560, 034020, 035420, 012450, 005380, 055550, 068270, 000270, 086790, 028260, 009540, 035720, 005490, 012330, 064350, 010140, 032830, 000810, 051910, 006400, 033780, 015760, 042660, 009150, 030200, 066570, 138040, 034730, 010130, 096770, 017670, 000100, 047810, 011200, 003550, 018260, 086280, 071050

### 미국
https://www.ssga.com/us/en/intermediary/etfs/spdr-sp-500-etf-trust-spy

In [7]:
nasdaq_ticker_list = read_csv_files("미국", "new_NASDAQ")

In [8]:
nyse_ticker_list = read_csv_files("미국", "new_NYSE")

In [14]:
usa_ticker_list = nasdaq_ticker_list + nyse_ticker_list

In [26]:
df = pd.read_excel("SPY_Holdings.xlsx", sheet_name="holdings")

if df.columns[0] != "Name":
    # Name 행이 나올 때까지 스킵 후 재로드
    df2 = pd.read_excel("SPY_Holdings.xlsx", sheet_name="holdings", header=4)
else:
    df2 = df

# 필요한 열만 남기고 비중 기준으로 내림차순 정렬
cols = ["Name", "Ticker", "Weight"]
df2 = df2[cols].copy()
df2["Weight"] = pd.to_numeric(df2["Weight"], errors="coerce")

df_spy = df2.dropna(subset=["Weight"]).sort_values(
    "Weight", ascending=False).reset_index(drop=True)
df_spy.head()

                         Name Ticker    Weight
0                 NVIDIA CORP   NVDA  7.672870
1              MICROSOFT CORP   MSFT  6.709179
2                   APPLE INC   AAPL  6.690392
3              AMAZON.COM INC   AMZN  3.764149
4  META PLATFORMS INC CLASS A   META  2.846779

In [46]:
cnt = 0
spy_top_list = []

for ticker in df_spy['Ticker']:
    if cnt == 100:
        break
    if ticker in usa_ticker_list:
        spy_top_list.append(ticker)
        cnt += 1

In [47]:
len(spy_top_list)

100

In [ ]:
print(", ".join(spy_top_list))

NVDA, MSFT, AAPL, AMZN, META, GOOGL, TSLA, JPM, LLY, V, XOM, ORCL, MA, WMT, JNJ, HD, ABBV, PG, BAC, GE, UNH, CVX, WFC, IBM, AMD, PM, KO, GS, CRM, ABT, RTX, CAT, MCD, DIS, T, MRK, NOW, MS, C, AXP, VZ, TMO, BA, BLK, SCHW, TJX, NEE, SPGI, APH, ACN, ANET, BSX, LOW, COF, PGR, ETN, UNP, PFE, BX, SYK, COP, MDT, DHR, WELL, DE, MO, PLD, CB, SO, LMT, MMC, CVS, ICE, PH, DUK, MCK, NEM, TT, KKR, AMT, BMY, GD, RCL, NKE, MMM, WM, PNC, NOC, SHW, WMB, AJG, BK, USB, AON, CI, MSI, MCO, TDG, EMR, ELV

In [39]:
spy_top_df = df_spy.head(100)

In [40]:
cnt = 1
spy_top_list = []
no_data_list = []
rank_list = []

for ticker in spy_top_df['Ticker']:
    if ticker in usa_ticker_list:
        spy_top_list.append(ticker)
    else:
        no_data_list.append(ticker)
        rank_list.append(cnt)
    cnt += 1

In [44]:
len(spy_top_list)

67

In [45]:
len(no_data_list)

33

In [43]:
rank_list

[6,
 9,
 10,
 14,
 21,
 22,
 30,
 38,
 42,
 47,
 49,
 53,
 54,
 55,
 56,
 58,
 61,
 62,
 64,
 66,
 68,
 69,
 73,
 80,
 82,
 83,
 84,
 86,
 90,
 92,
 93,
 97,
 98]

### 일본
https://nextfunds.jp/en/lineup/1321/#tab-summary

In [84]:
tse_ticker_list = read_csv_files("일본", "new_TSE")
tse_ticker_list = [s.removesuffix(".T") for s in tse_ticker_list]

In [76]:
df = pd.read_excel("1321.T_Holdings.xlsx", sheet_name="holdings", header=2)

rename_map = {
    "No.": "Rank",
    "銘柄コード_x000D_\n（Code）": "Code",
    "銘柄_x000D_\n（Name）": "NameJP",
    # "Name": "NameEN",
    "株数（※）_x000D_\nNo. of Shares（※）": "Shares",
    "評価金額(円）_x000D_\nValuation (yen)": "ValuationJPY",
    "純資産比率_x000D_\n% of NAV": "Weight"
}

df = df.rename(columns=rename_map)

# 필요한 열만 남기고 비중 기준으로 내림차순 정렬
cols = ["Name", "Code", "Weight"]
df = df[cols].copy()
df["Weight"] = pd.to_numeric(df["Weight"], errors="coerce")

df_1321 = df.dropna(subset=["Weight"]).sort_values(
    "Weight", ascending=False).reset_index(drop=True)
df_1321 = df_1321.iloc[2:].reset_index(drop=True)
df_1321.head()

                      Name  Code    Weight
0  FAST RETAILING CO.,LTD.  9983  0.086671
1     SOFTBANK GROUP CORP.  9984  0.075595
2    ADVANTEST CORPORATION  6857  0.072505
3   TOKYO ELECTRON LIMITED  8035  0.048126
4         KDDI CORPORATION  9433  0.023759

In [87]:
cnt = 0
tse_top_list = []

for ticker in df_1321['Code']:
    if cnt == 45:
        break
    if ticker in tse_ticker_list:
        tse_top_list.append(ticker)
        cnt += 1

In [88]:
len(tse_top_list)

45

In [89]:
print(", ".join(tse_top_list))

9983, 9984, 6857, 8035, 9433, 6762, 6098, 4063, 9766, 4543, 6954, 6758, 4519, 6367, 6988, 6971, 7832, 7203, 7974, 5803, 8015, 9735, 4568, 4901, 8058, 7267, 7741, 8766, 6902, 8001, 6146, 4503, 2802, 7269, 4704, 4578, 4507, 7733, 8031, 9843, 3659, 4452, 5108, 7751, 7453

In [90]:
tse_top_df = df_1321.head(45)

In [91]:
cnt = 1
tse_top_list = []
no_data_list = []
rank_list = []

for ticker in tse_top_df['Code']:
    if ticker in tse_ticker_list:
        tse_top_list.append(ticker)
    else:
        no_data_list.append(ticker)
        rank_list.append(cnt)
    cnt += 1

In [92]:
len(tse_top_list)

44

In [93]:
len(no_data_list)

1

### 중국
https://fundf10.eastmoney.com/ccmx_510300.html

In [98]:
sse_ticker_list = read_csv_files("중국", "new_SSE")
sse_ticker_list = [s.removesuffix(".SS") for s in sse_ticker_list]

In [122]:
df = pd.read_csv("510300.SS_Holdings.csv")

rename_map = {
    "Stock Code": "Code",
    "Stock Name": "Name",
    "Percentage of net worth": "Weight"
}
df = df.rename(columns=rename_map)

# 필요한 열만 남기고 비중 기준으로 내림차순 정렬
cols = ["Name", "Code", "Weight"]
df = df[cols].copy()
df["Code"] = pd.to_numeric(df["Code"], errors="coerce").astype("Int64").astype(str)
df["Weight"] = df["Weight"].astype(str).str.rstrip("%").astype(float)

df_510300 = df.dropna(subset=["Weight"]).reset_index(drop=True)
df_510300.head()

                   Name    Code  Weight
0       Kweichow Moutai  600519    4.21
1                  CATL  300750    3.16
2      Ping An of China  601318    2.83
3  China Merchants Bank  600036    2.70
4       Industrial Bank  601166    1.83

In [125]:
cnt = 0
sse_top_list = []

for ticker in df_510300['Code']:
    if cnt == 60:
        break
    if ticker in sse_ticker_list:
        sse_top_list.append(ticker)
        cnt += 1

In [126]:
len(sse_top_list)

60

In [127]:
print(", ".join(sse_top_list))

600519, 601318, 600036, 601166, 600900, 601899, 600030, 601398, 600276, 601328, 601288, 600887, 600000, 601088, 601601, 601668, 600016, 600031, 603019, 600309, 601169, 601857, 601919, 600690, 600660, 601012, 601688, 600406, 601766, 600809, 600050, 600028, 601988, 601006, 601818, 601225, 600104, 600150, 601628, 601009, 600999, 603288, 600760, 601939, 600111, 600089, 600436, 601888, 603993, 600048, 600547, 600019, 601390, 600415, 601600, 600893, 600585, 600570, 600958, 603799